Chatterbox/urls.py
from django.contrib import admin
from django.contrib.auth.models import User, Group
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import path

import accounts.views
import base.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', base.views.hello),
    path('', base.views.RoomsView.as_view(), name='rooms'),
    path('room/detail/<pk>/', base.views.room, name='room'),
    path('room/create/', base.views.RoomCreateView.as_view(), name='room_create'),
    path('room/edit/<pk>', base.views.RoomUpdateView.as_view(), name='room_update'),
    path('room/delete/<pk>', base.views.RoomDeleteView.as_view(), name='room_delete'),

    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),
    path('accounts/password_change/', PasswordChangeView.as_view(template_name="registration/password_change.html"), name='password_change'),
    path('accounts/password_change/done', PasswordChangeDoneView.as_view(template_name="registration/password_change_done.html"), name='password_change-done'),

    path('accounts/signup/', accounts.views.SignUpView.as_view(), name='signup'),

    path('search/', base.views.search, name='search')
]

handler403 = 'base.views.handler403'


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        instance.groups.add(Group.objects.get(name='Participants'))

base/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Model

# Create your models here.
from django.template.defaultfilters import truncatechars


class Room(Model):
    name = models.CharField(max_length=200, unique=True)  # Zadáváme název místnosti
    description = models.TextField(null=True, blank=True)  # Umožníme zadání popisku místnosti - může být prázdný (null) nebo i jen whitespaces (blank)
    participants = models.ManyToManyField(User, related_name='participants', blank=True)  # Přidání uživatelů účastnících se konverzace v místnosti - vztah Many to Many
    created = models.DateTimeField(auto_now_add=True)  #Přidání času vytvoření místnosti
    updated = models.DateTimeField(auto_now=True)  #Přidání času modifikace místnosti

    def __str__(self):  # Formátování, jak se má zobrazit class jako string
        return self.name

    class Meta:
        ordering = ['-created', 'name']  # Seřazení místností podle data vytvoření (pomocí - od nejnovějšího po nejstarší), pokud by byly stejné tak podle jména


class Message(Model):
    body = models.TextField()
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    @property
    def body_short(self):
        return truncatechars(self.body, 50)

    def __str__(self):
        return self.body[0:50]

    class Meta:
        ordering = ['-created', 'body']

templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href=“http://fonts.googleapis.com/css?family=Arvo” rel=“stylesheet” type=“text/css”/>
    <link href=“http://fonts.googleapis.com/css?family=Bevan” rel=“stylesheet” type=“text/css”/>
    <link rel="stylesheet" href="{% static 'styles/style.css' %}"/>
    <title>Title</title>
</head>
<body>
    <div id="wrapper">
        <div id="header">
            <div id="logo">
                <h1 id="logo h1">Chatterbox</h1>
            </div>
            {% if user.is_authenticated %}
            <div id="search">
                <form action="{% url 'search' %}" method="get">
                    <div>
                        <input class="text" name="q">
                    </div>
                </form>
            </div>

            <div id="menu">
                {% include 'navbar.html' %}
            </div>
            {% endif %}
        </div>
        <div id="page">
            <div id="content">
                {% block content %}
                {% endblock %}
                <br class="clearfix">
            </div>
            <br class="clearfix">
        </div>
    </div>
</body>
</html>

templates/navbar.html
<ul>
    <li class="first active">
        <a href="{% url 'rooms' %}">Rooms</a>
    </li>
    {% if perms.base.add_room %}
    <li>
        <a href="{% url 'room_create' %}">Create room</a>
    </li>
    {% endif %}


    {% if user.is_authenticated %}
    <li class="last-child">
        <a href="{% url 'logout' %}">Logout</a>
    </li>
    <li class="last-child">
        <a href="{% url 'password_change' %}">Change password</a>
    </li>
    <li class="last-child">
        {{user.username}}
    </li>

    {% else %}
    <li class="last-child">
            <a href="{% url 'login' %}">Login</a>
    </li>
    {% endif %}


</ul><br class="clearfix"/>