Chatterbox/urls.py
from django.contrib import admin
from django.contrib.auth.models import User, Group
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import path

import accounts.views
import base.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', base.views.hello),
    path('', base.views.RoomsView.as_view(), name='rooms'),
    path('room/detail/<pk>/', base.views.room, name='room'),
    path('room/create/', base.views.RoomCreateView.as_view(), name='room_create'),
    path('room/edit/<pk>', base.views.RoomUpdateView.as_view(), name='room_update'),
    path('room/delete/<pk>', base.views.RoomDeleteView.as_view(), name='room_delete'),

    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),
    path('accounts/password_change/', PasswordChangeView.as_view(template_name="registration/password_change.html"), name='password_change'),
    path('accounts/password_change/done', PasswordChangeDoneView.as_view(template_name="registration/password_change_done.html"), name='password_change-done'),

    path('accounts/signup/', accounts.views.SignUpView.as_view(), name='signup'),

    path('search/', base.views.search, name='search')
]

handler403 = 'base.views.handler403'


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        instance.groups.add(Group.objects.get(name='Participants'))

base/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Model

# Create your models here.
from django.template.defaultfilters import truncatechars


class Room(Model):
    name = models.CharField(max_length=200, unique=True)  # Zadáváme název místnosti
    description = models.TextField(null=True, blank=True)  # Umožníme zadání popisku místnosti - může být prázdný (null) nebo i jen whitespaces (blank)
    participants = models.ManyToManyField(User, related_name='participants', blank=True)  # Přidání uživatelů účastnících se konverzace v místnosti - vztah Many to Many
    created = models.DateTimeField(auto_now_add=True)  #Přidání času vytvoření místnosti
    updated = models.DateTimeField(auto_now=True)  #Přidání času modifikace místnosti

    def __str__(self):  # Formátování, jak se má zobrazit class jako string
        return self.name

    class Meta:
        ordering = ['-created', 'name']  # Seřazení místností podle data vytvoření (pomocí - od nejnovějšího po nejstarší), pokud by byly stejné tak podle jména


class Message(Model):
    body = models.TextField()
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    @property
    def body_short(self):
        return truncatechars(self.body, 50)

    def __str__(self):
        return self.body[0:50]

    class Meta:
        ordering = ['-created', 'body']

base/forms.py
from logging import getLogger

from django import forms
from django.core.exceptions import ValidationError
from django.forms import Form, Textarea, ModelForm
from base.models import Room

# Třida určená pro View s děděním od FormView
# class RoomForm(Form):
#     name = forms.CharField(max_length=200)
#     description = forms.CharField(widget=Textarea, required=False)

# Třída určená pro View s děděním od CreateView

LOGGER = getLogger()


class RoomForm(ModelForm):
    class Meta:
        model = Room
        fields = '__all__'
        exclude = ['participants']

    def clean_name(self):
        name = self.cleaned_data['name']
        if len(name) < 2:
            validation_error = "Name should contain at least 2 characters"
            LOGGER.warning(f'{validation_error}: {name}')
            raise ValidationError(validation_error)
        return name

base/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, FormView, CreateView, DeleteView, UpdateView

from base.forms import RoomForm
from base.models import Room, Message

# Create your views here.


def hello(request):
    s = request.GET.get('s', '')
    return HttpResponse(f"Hello {s}!")


@login_required
@permission_required(['base.view_room'])
def search(request):
    q = request.GET.get('q', '')
    rooms = Room.objects.filter(
        Q(name__icontains=q) |
        Q(description__icontains=q)
    )
    context = {'object_list': rooms}
    return render(request, 'base/rooms.html', context)


# def rooms(request):
#     rooms = Room.objects.all()  # získání názvu všech místností
#     context = {'rooms': rooms}  # přidání vazby na html soubor (ve for loopě je 'rooms')
#     return render(request, template_name='base/rooms.html', context=context)  # renderování stránky


# class based view - využívá parent classu, abychom neuseli psát tolik kódu - o return a proměnnou méně než v
# zakomentovaném kódu nahoře
#Je ale potřeba v URL přepsat cestu na ....RoomsView.as_view()
# class RoomsView(TemplateView):
#     template_name = 'base/rooms.html'
#     extra_context = {'rooms': Room.objects.all()}

#Děděním z ListView není možné filtrovat výsledky!!! Jde o základní nejjednodušší třídní view
#Vrací kontext object_list, proto je ptořeba v HTML souboru toto přepsat


class RoomsView(PermissionRequiredMixin, LoginRequiredMixin, ListView):
    template_name = 'base/rooms.html'
    model = Room
    permission_required = ['base.view_room']


@login_required
@permission_required(['base.view_room', 'base.view_message'])
def room(request, pk):
    room = Room.objects.get(id=pk)  # získání místnosti podle id

    #POST
    if request.method == "POST":
        if request.user.has_perm('base.add_message'):
            Message.objects.create(
                user=request.user,
                room=room,
                body=request.POST.get('body')
            )
            room.participants.add(request.user)
            room.save()
            return redirect('room', pk=pk)

    #GET
    messages = room.message_set.all()  # vybrání všech zpráv v dané místnosti
    context = {'messages': messages, 'room': room}  # předání proměnných pro HTML soubor
    return render(request, template_name='base/room.html', context=context)  # render webovky

# Tato třída je ta samá jako ta s Create view, jen je delší zápis
# class RoomCreateView(FormView):
#     template_name = 'base/room_form.html'
#     form_class = RoomForm
#     success_url = reverse_lazy('rooms')
#
#     def form_valid(self, form):
#         cleaned_data = form.cleaned_data
#         Room.objects.create(
#             name=cleaned_data['name'],
#             description=cleaned_data['description']
#         )
#         return super().form_valid(form)

# Stejné jako nahoře, jen je potřeba do form.py přidat třídu Meta


class RoomCreateView(PermissionRequiredMixin, LoginRequiredMixin, CreateView):
    template_name = 'base/room_form.html'
    form_class = RoomForm
    extra_context = {'title': 'Create room'}
    success_url = reverse_lazy('rooms')
    permission_required = ['base.add_room']


class RoomUpdateView(PermissionRequiredMixin, LoginRequiredMixin, UpdateView):
    template_name = 'base/room_form.html'
    form_class = RoomForm
    extra_context = {'title': 'Update room'}
    success_url = reverse_lazy('rooms')
    model = Room
    permission_required = ['base.change_room']


class StaffRequiredMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_staff


class RoomDeleteView(StaffRequiredMixin, PermissionRequiredMixin, LoginRequiredMixin, DeleteView):
    template_name = 'base/room_confirm_delete.html'
    model = Room
    success_url = reverse_lazy('rooms')
    permission_required = 'base.delete_room'


def handler403(request, exception):
    return render(request, '403.html', status=403)

base/templates/base/room.html
{% extends 'main.html' %}

{% block content %}
    <h1>{{ room.name }}</h1>
    <br>
    <div class="box">{{ room.description }}</div>
    {% if perms.base.add_message %}
    <div class="box room__message">
        <form method="post">
            {% csrf_token %}
            <input name="body" placeholder="Write your message here ..."/>
        </form>
    </div>
    {% endif %}

        {% for message in messages %}
            <div class="box">
            {% if message.user == user %}
                <div style="float:right"><b>{{ message.user }}</b> <i>[{{ message.created }}]</i></div>
                <div class="message"
                     style = "float: right;
                                color: white;
                                background: #e16060;">
                    {{ message.body }}
                </div>
            {% else %}
                <div><b>{{ message.user }}</b> <i>[{{ message.created }}]</i></div>
                <div class="message">{{ message.body }}</div>
            {% endif %}
            </div>
        {% endfor %}
{% endblock %}

base/templates/base/room_confirm_delete.html
{% extends 'main.html' %}

{% block content %}
    <h1>Delete room</h1>
    <form method="post">
        {% csrf_token %}
        <div class="box">
            <p>Are you sure you want to delete "{{ object.name }}"?</p>
            <button type="submit">Yes</button>
            <a href="{% url 'rooms' %}">Cancel</a>
        </div>
    </form>
{% endblock %}

base/templates/base/room_form.html
{% extends 'main.html' %}

{% block content %}
    <h1>{{ title }}</h1>
    <br>
    <form method="post">
        {% csrf_token %}
        <div class="box">
            <label for="{{ form.name.id_for_label }}">Room name</label>
            {{ form.name }}
            {{ form.name.errors }}
            <br>
            <label for="{{ form.description.id_for_label }}" style="vertical_align: top">Description</label>
            {{ form.description }}
        </div>
        <button type="submit">Submit</button>
    </form>
{% endblock %}

base/templates/base/rooms.html
{% extends 'main.html' %}

{% block content %}
    <h1>Rooms</h1>
    <br>
    <div class="box">
        {% for room in object_list %}
            <div style="float: left;">
                <a href="{% url 'room' room.id %}">{{ room.name }}</a>
                <br>
                {{room.description}}
            </div>
            <div style="float: right;">
                {% if perms.base.change_room %}
                    <a href="{% url 'room_update' room.id %}">Edit</a>
                {% endif %}

                {% if perms.base.delete_room and perms.base.delete_message and user.is_staff %}
                    <a href="{% url 'room_delete' room.id %}">Delete</a>
                {% endif %}
            </div>
        <br class="clearfix">
        {% endfor %}
    </div>
{% endblock %}